### PR TITLE
Add word-level diffs for WPF controls.

### LINKED ISSUE #53: Word Level Diffing in the SideBySideDiffViewer WPF Control
Is there a way to do Word level diffing in the SideBySideDiffViewer WPF Control that I'm missing, or does that only support line level?

### PR DESCRIPTION
**Pull request by kingcean**
Controls `DiffViewer`, `InternalLinesViewer` and `SideBySideDiffViewer` support sub-piece diffs by default now.

> Fix #53 issue.

It is dependent on that the diffs result `DiffPaneModel` computed from diff builder (such as `SideBySideDiffBuilder`) contains sub-pieces information.

Following is an example.

```xaml
<diffplex:DiffViewer x:Name="DiffView" />
```
```csharp
DiffView.OldText = oldText;
DiffView.NewText = newText;
```

Diff sample

And following is another example.

```xaml
<diffplex:SideBySideDiffViewer x:Name="DiffView" />
```
```csharp
DiffView.SetDiffModel(OldText, NewText);
```

Note: It will be disabled when the text is too large (more than 3K lines) because of performance.

This PR also contains the changes of performance improvement to async render result for side-by-side mode.

### CODE REVIEW

**Comment by kingcean** [comment]
Need upload DiffPlex package into NuGet before DiffPlex.Wpf package because the latter is dependent on the new version of the former.

**Comment by mmanela** [comment]
Done and published

**Comment by kingcean** [comment]
@mmanela Sounds NuGet package DiffPlex v1.6.0 contains the assembly (DiffPlex.dll) v1.5.0 actually but expect v1.6.0. You can have a test by installing it into a test project and checking the version of the dll referenced.
https://www.nuget.org/packages/DiffPlex/1.6.0

**Comment by mmanela** [comment]
I just published. Should be fixed. let me know

**Comment by kingcean** [comment]
@mmanela It works now.

**Pull request merged**
