### PR TITLE
Generate AppVeyor artifacts upon building

### PR DESCRIPTION
**Pull request by igitur**
This addition to the CI build will generate the NuGet packages as artifacts. This should ease the process to get a new version on NuGet.

Please rebase, not merge.

### CODE REVIEW

**Comment by igitur** [comment]
Notice the `.nupkg` artifacts at https://ci.appveyor.com/project/mmanela/diffplex/build/1.4.18/artifacts

**Comment by mmanela** [comment]
Thanks!

**Comment by igitur** [comment]
Pleasure. Would you mind uploading the package at https://ci.appveyor.com/project/mmanela/diffplex/build/1.4.20/artifacts to NuGet sometime?

**Comment by igitur** [comment]
Maybe you would just want to check the metadata first

**Comment by mmanela** [comment]
Done

**Pull request merged**
