### PR TITLE
Add WPF controls

### PR DESCRIPTION
**Pull request by kingcean**
Contains following WPF controls in project `DiffPlex.Wpf`.

- `DiffPlex.Wpf.Controls.SideBySideDiffViewer` Side-by-side diffs viewer control.
- `DiffPlex.Wpf.Controls.InlineDiffViewer` Inline diffs viewer control.

You can customize the foregrounds and backgrounds for each change type of line.

### Sample

Following is an example for side by side diff viewer control.

```xaml
<diffplex:SideBySideDiffViewer x:Name="SideBySideDiff" />
```

```csharp
var builder = new SideBySideDiffBuilder(new Differ());
SideBySideDiff.DiffModel = builder.BuildDiffModel(OldText, NewText);
```

The project `DiffPlex.Wpf.Demo` is a simple demo you can see for details.

DiffPlexWpfDemo

### CODE REVIEW

**Comment by kingcean** [comment]
Need update the build service to use the SDK of .NET Core 3.1 to build.

**Comment by mmanela** [comment]
Thanks for the PR, I updated master to ensure core 3.1 is run

**Comment by kingcean** [comment]
So will you merge this pull request and upload a new nuget package?

**Comment by mmanela** [comment]
@kingcean This looks great. Can you also update the readme to add a section about this? Maybe a screen shot and a sample code?

**Comment by kingcean** [comment]
OK. Updated.

**Comment by mmanela** [comment]
Thanks Ill take a look soon

**Comment by mmanela** [comment]
@kingcean  Published https://www.nuget.org/packages/DiffPlex.Wpf/

**Pull request merged**
