### PR TITLE
sample code ForegroundColor issues

### PR DESCRIPTION
**Pull request by daveyostcom**
• I thought Gray might be a better compromise here for dark mode or not. YMMV.
• Isn't Red more usual for deletions?
• The code leaves the console with a different ForegroundColor.

### CODE REVIEW

**Comment by mmanela** [comment]
@daveyostcom Can you paste screen shot?

**Comment by daveyostcom** [comment]
There's nothing special to see, really. The code in question is not covered because it never runs, and that's because it should never run. I think we should be able to annotate the code to make such code look covered even though it doesn't run.

**Comment by daveyostcom** [comment]
Disregard my Red-Green confusion. The colors are used correctly.

**Comment by daveyostcom** [comment]
Showing unchanged lines in gray:
image
Showing unchanged lines in white makes them invisible.

**Pull request merged**
