### PR TITLE
Add summary text of line additions and deletions for WinUI library

### PR DESCRIPTION
**Pull request by kingcean**
Optimize `DiffPlex.Window`.

- Add a text block on top right of the diff view to show lines of addition and deletion.
- Fix an issue cause there is no change symbol mark in unified view.

### CODE REVIEW

**Comment by kingcean** [comment]
Hi @mmanela could you please upload `DiffPlex.Windows` assembly to NuGet?

For your information, it requires following development environment to build.

https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/set-up-your-development-environment?tabs=vs-2022-17-1-a%2Cvs-2022-17-1-b

**Comment by kingcean** [comment]
Hello @mmanela the `DiffPlex.Windows` project/assembly is introduced by #96 for Windows App SDK (with WinUI 3) and is available to publish on NuGet. Could you please package and upload it? You can also use the NuPkg file and its symbol file directly from following compressed file.

[DiffPlex.Windows.1.0.0.zip](https://github.com/mmanela/diffplex/files/9738689/DiffPlex.Windows.1.0.0.zip)

**Comment by mmanela** [comment]
@kingcean  Oh so you already built it? That is nice of you :)

**Comment by mmanela** [comment]
Submitted

**Pull request merged**
